from typing import Any, Protocol


class IntervalsReadClient(Protocol):
    async def list_activities(self, oldest: str, newest: str) -> list[dict[str, Any]]: ...

    async def get_activity(self, activity_id: str, intervals: bool = True) -> dict[str, Any]: ...

    async def list_wellness(self, oldest: str, newest: str) -> list[dict[str, Any]]: ...

    async def list_events(self, oldest: str, newest: str) -> list[dict[str, Any]]: ...

    async def get_sport_settings(self) -> list[dict[str, Any]]: ...


class IntervalsCalendarClient(Protocol):
    async def list_events(
        self, oldest: str, newest: str, category: str | None = None
    ) -> list[dict[str, Any]]: ...

    async def get_event(self, event_id: str) -> dict[str, Any]: ...

    async def create_event(self, payload: dict[str, Any]) -> dict[str, Any]: ...

    async def update_event(self, event_id: str, payload: dict[str, Any]) -> dict[str, Any]: ...

    async def delete_event(self, event_id: str) -> None: ...
