from typing import Any, Protocol


class IntervalsReadClient(Protocol):
    async def list_activities(self, oldest: str, newest: str) -> list[dict[str, Any]]: ...

    async def get_activity(self, activity_id: str, intervals: bool = True) -> dict[str, Any]: ...

    async def list_wellness(self, oldest: str, newest: str) -> list[dict[str, Any]]: ...

    async def list_events(self, oldest: str, newest: str) -> list[dict[str, Any]]: ...

    async def get_sport_settings(self) -> list[dict[str, Any]]: ...
